### ISSUE TITLE
Support for windows systems

### ISSUE THREAD

**Issue by olee** [reidarsollid/RustyCage#25]
Please try to fix the problem for windows systems.
As it has already been mentioned once, the only problem seems to be the use of incorrect exe-path for the compiler.
A possible fix would be changing the settings field for the compiler from a directory to a full file path and using that one when running it.
If you could tell me where in the sources I can find the call to the compiler I would even try to fix this myself.

**Comment by reidarsollid** [comment]
There really has not been a problem, I have not supported it so this is not a bug but a feature request.

If you try change the compiler path to the one you use in windows I hope this is enough ?
![screen shot 2015-01-08 at 23 25 02](https://cloud.githubusercontent.com/assets/717858/5672086/a7479f7a-978d-11e4-81f7-d4c703142b77.png)

The update site with test software is herer:
https://sourceforge.net/projects/rustycage/files/updatesite-windows-test/

If you could test it, that would be great.

**Comment by armink** [comment]
@reidarsollid  Thx a lot.

**Comment by armink** [comment]
It has some problem on windows platform. Always stop at `Compiling: L/xx/src/xx.rc·`line.
How can I find the problem reasons? Link Plug-in log... @reidarsollid 
![qq 20150111225609](https://cloud.githubusercontent.com/assets/1734686/5695571/1260578e-99e6-11e4-8fbb-aac29d9f4411.png)

**Comment by reidarsollid** [comment]
You must add /rustc.exe to the compile paths so that it is 
So that it is "C:\Rust\bin\rustc.exe" Ignore the message "Value must be existing directory"

**Comment by armink** [comment]
@reidarsollid Ok, I waiting for the Windows version. Thx. :smile:

**Comment by reidarsollid** [comment]
Added windows support for updatesite-luna, tested on Win8.

**Comment by armink** [comment]
Good!!!
I tried it ok. But autocomplete function seems does not work well on windows.
