### ISSUE TITLE
Scala compiler for installation site is too old to installation fail

### ISSUE THREAD

**Issue by armink** [reidarsollid/RustyCage#27]
I try to download the Scala compiler by the default installation site on home page many times. But the Eclipse also say "`No repository found containing: osgi.bundle,org.scala-ide.sbt.full.library,0.13.0.M2-2_10-20130710-1841`". And I changed the installation site to "`http://download.scala-ide.org/sdk/lithium/e44/scala211/stable/site/`". The Scala compiler finally successful installation. So I think the default installation site on home page is too old. 
My platform is Windows. Using Eclipse Luna for C/C++.

**Comment by reidarsollid** [comment]
Thanks, I have changed the readme file to the correct Scala updatesite.
